config/routes.rb
Rails.application.routes.draw do
  resources :tarefas
  resources :usuarios
  post 'usuarios/:id', to: 'usuarios#desativar'
  post 'tarefas/:id', to: 'tarefas#concluir'
  root 'sessions#new'
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    #Utilizando o bcrypt
    has_secure_password

    #validações para não ser nulos e email único
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
    validates :name, presence: true
    validates :name, length: {minimum:3}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    helper_method :logged_in?, :current_user

    def current_user
      if session[:usuario_id]
        @usuarioLogado = Usuario.find(session[:usuario_id])
      end
    end
  
    def logged_in?
      !!current_user
    end
  
    def authorized
      redirect_to login_path unless logged_in?
    end

    def set_locale
      locale = params[:locale] || cookies[:locale]
      if locale.present?
        I18n.locale = locale
        cookies[:locale] = { value: locale, expires: 30.days.from_now}
      else
        I18n.locale = 'en'
      end
     end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "login"
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  layout "login"
    def new
    end
  
    def create
      @usuarioLogado = Usuario.find_by(email: params[:email])
      if @usuarioLogado && @usuarioLogado.authenticate(params[:password])
        session[:usuario_id] = @usuarioLogado.id
        redirect_to tarefas_path
      else  
        redirect_to login_path
      end
    end

    def destroy
        session[:usuario_id] = nil
        redirect_to login_path
      end
    
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy, :concluir]
  before_action :authorized
  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.where(:usuario_id=>@usuarioLogado.id, :status=>"Em Andamento")
    @tarefasDone = Tarefa.where(:usuario_id=>@usuarioLogado.id, :status=>"Concluída")
  end

  def concluir
    # @usuario = Usuario.find(params[:id])
     #Usuario.update(@usuario.id, status:10) 
     
       @tarefa.update_attribute(:status, "Concluída")
       msg = "Desativado"
     
     redirect_to tarefas_path, notice: msg
   end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to tarefas_path, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to tarefas_path, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarefa_params
      params.require(:tarefa).permit(:descricao, :status, :prazo, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy, :desativar]
  before_action :authorized

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all.order(:name)
  end

  def desativar
   # @usuario = Usuario.find(params[:id])
    #Usuario.update(@usuario.id, status:10) 
    if(@usuario.status!=0)
      @usuario.update_attribute(:status, 0)
      msg = "Desativado"
    else
      @usuario.update_attribute(:status, 1)
      msg = "Ativado"
    end   
    redirect_to usuarios_path, notice: msg
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuarios_path, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuarios_path, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:id, :name, :email, :password, :password_confirmation, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/base/_footer.html.erb
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

app/views/base/_header.html.erb
<div class="d-flex justify-content-end sm">
  <div class="text-white "><%= link_to t('versionE'), locale: "en" %></div>
  <div>&nbsp &nbsp&nbsp &nbsp</div>
  <div class="text-white"><%= link_to t('versionP'), locale: "pt-BR" %></div>
</div>

app/views/base/_sidebar.html.erb
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="projects.html" class="brand-link">
      <img src="/img/AdminLTELogo.png"
           alt="Devworks Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">DevworksSTC</span>
    </a>


    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <% if logged_in? %>
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">   
          <div class="image">
            <img src="/img/avatar5.png" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="text-white">
            <p><%=current_user.name%>
            <%= link_to t('logout'), sessions_path, method: :delete, class:"d-block" %></p>
          </div>
        </div>
      <%end%>
      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="/tarefas" class="nav-link">
              <i class="nav-icon fas fa-tasks"></i>
              <p>
                <%= t('tasks')%>
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="/usuarios" class="nav-link" value="menuUser">
              <i class="nav-icon fas fa-user-plus"></i>
              <p>
              <%= t('users')%>
              </p>
            </a>
          </li>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/home/index.html.erb
<form action="/usuarios" method="get">

          <div class="input-group mb-3">
            <input type="email" class="form-control" placeholder="<%=t('password')%>">
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          </div>

          <div class="input-group mb-3">
            <input type="password" class="form-control" placeholder="Password">
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          
          <div class="row">
            <div class="col-8">
              <div class="icheck-primary">

              </div>
            </div>
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block">Sign Ieddn</button>
            </div>
          </div>

        </form> 

        <p class="mb-1">
          <a href="forgot-password.html">Esqueci a minha senha...</a>
        </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevWorks-SCT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-scrollbar-auto-hide="n" class="hold-transition sidebar-mini layout-fixed">
      <div class="wrapper">
        <%= render "base/header" %>
        <%= render "base/sidebar" %>

        <div class="content-wrapper">
         <div class="content container-fluid">
            <div class="container-fluid">
                <%= yield %>
            </div>
          </div>
        </div>
        <%= render "base/footer" %>
        <%= render "base/control_sidebar" %>
      <div>
  </body>
</html>

app/views/layouts/login.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <title>DevWorks | Sistema de Controle de Tarefas (SCT) </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %></head>

  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <i class="fab fa-stack-overflow"></i><b>DevWorks</b>SCT
      </div>

      <div class="card">
        <div class="card-body login-card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  </html>

app/views/tarefas/_form.html.erb
<div class="col-sm-6">
  <h2><i class="fas fa-puzzle-piece"></i><%=t('newTask')%></h2>
</div>
<section class="content">
      <!-- Default box -->
      <div class="card">
        <div class="card-body">
        <%= form_with(model: tarefa, local: true) do |form| %>
          <% if tarefa.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>
              <ul>
                <% tarefa.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><%=t('taskInformation')%></h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <form action="tasks.html" method="post">
            <div class="card-body">
              
              <div class="form-group">
                <%= form.label t('taskDesc') %>
                <%= form.text_area :descricao, class:"form-control" , placeholder:t('taskTypeDesc') %>
              </div>
              <div class="form-group ">
              <%= form.label t('responsible') %>
              <%= form.select :usuario_id, Usuario.where(status:1).collect {|p| [ p.name, p.id ]},{},{:class=>'form-control'}%>
                 
              </div>
              <div class="form-group">
                 <%= form.label t('deadline') %><BR>
                <%= form.date_select :prazo, class:"form-control" %>
              </div>
              <div class="d-none">
                  <label>Status</label>
                  <%= form.select :status, [['Em Andamento', 'Em Andamento']], {},{:class=>'form-control'} %>
                </div>
              
              <div class="box-footer">
              <%= form.submit t('register'), class:"btn btn-success right"  %>
              <%= link_to t('cancel'), tarefas_path, type:'button', class: "btn btn-secondary" %>
              </div>

              
            <%end%>
            </div>
            <!-- /.card-body -->

          </div>
        </div>
        
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>

app/views/tarefas/edit.html.erb
<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<div class="col-sm-6">
  <h1><i class="fas fa-tasks"> </i> <%=t('tasks')%> </i></h1>
</div>
<section class="content">
  <div class="card">
    <div class="card-header">
      <div id="notice"><%= notice %></div>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button>
        </div>
    </div>
  
    <div class="card-body p-0">
      <table class="table table-striped projects">
          <thead>
              <tr>
                  <th style="width: 1%">
                      #
                  </th>
                  <th style="width: 20%">
                      <%=t('taskDesc')%>
                  </th>
                  <th style="width: 20%">
                    <%=t('responsible')%>
                  </th>
                  <th>
                    <%=t('deadline')%>
                  </th>
                  <th style="width: 8%" class="text-center">
                      Status
                  </th>
                  <th style="width: 30%">
                  </th>
              </tr>
          </thead>
          <% @tarefas.each do |tarefa| %>
          <tbody>
              <tr>
                  <td>
                      #
                  </td>
                  <td>
                    <%= tarefa.descricao %>
                  </td>
                  <td>
                    <%# não sei se é a melhor forma para puxar nome %>
                    <%= Usuario.find(tarefa.usuario_id).name%>
                  </td>
                  <td>
                     <%= tarefa.prazo %>
                  </td>
                  <td class="project-state">
                      <span class="badge badge-warning"><%= tarefa.status %></span>
                  </td>
                  <td class="project-actions text-right">
                          
                            <%= link_to '<i class="fas fa-calendar-check"></i> Editar'.html_safe, edit_tarefa_path(tarefa), type:'button', class: "btn btn-success btn-sm" %>
                        
                            <%= link_to 'Excluir <i class="fas fa-pencil-alt"></i>'.html_safe, tarefa, method: :delete, class: "btn btn-info btn-sm", data: { confirm: 'Are you sure?' } %>
                            
                         

                            <%= link_to 'Concluir <i class="fas fa-share-square"></i>'.html_safe, tarefa, method: :concluir, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure ?' } %>
                            
                      </td>
              </tr>  
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
 </section>
 <div class="row">
 <div class="col-md-12 text-right">
   <%= link_to t('newTask'), new_tarefa_path, class: "btn btn-primary" %>
 </div>
 </div>
 <BR><BR>
 <div class="row">
  <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 25%" colspan="5">
                        <%=t('taskDone')%>
                    </th>
                </tr>
            </thead>
            <% @tarefasDone.each do |tarefa| %>
            <tbody>
                <tr>
                    <td>
                      <%= tarefa.descricao %>
                    </td>
                    <td>
                      <%# não sei se é a melhor forma para puxar nome %>
                      <%= Usuario.find(tarefa.usuario_id).name%>
                    </td>
                    <td>
                      <%= tarefa.prazo %>
                    </td>
                    <td class="project-state">
                        <span class="badge badge-danger"><%= tarefa.status %></span>
                    </td>
                </tr>  
            </tbody>
          <% end %>
        </table>
      </div>
</div>

app/views/tarefas/new.html.erb
<%= render 'form', tarefa: @tarefa %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tarefa.descricao %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tarefa.status %>
</p>

<p>
  <strong>Prazo:</strong>
  <%= @tarefa.prazo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @tarefa.usuario_id %>
</p>

<%= link_to 'Edit', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Back', tarefas_path %>

app/views/usuarios/_form.html.erb
<div class="col-sm-6">
  <h1><i class="fas fa-users"> </i> <%= t('users')%></i></h1>
</div>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- form start -->
            <%= form_with(model: usuario, local: true) do |form| %>
              <% if usuario.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

                  <ul>
                    <% usuario.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul> 
                </div>
              <%end%>

              <div class="box-body">
                <div class="form-group">
                    <%= form.label t('fullName') %>
                    <%= form.text_field :name, class:"form-control" , placeholder:t('enterFullName') %>
                </div>
                <div class="form-group">
                  <%= form.label :"Email" %>
                  <%= form.email_field :email, class:"form-control" , placeholder:"Enter email" %>
                </div>
                <div class="form-group">
                  <%= form.label t('password') %>
                  <%= form.password_field :password, class:"form-control" , placeholder:t('enterPassword') %>
                </div>
                <div class="form-group">
                 <%= form.label t('confirmPassword') %>
                  <%= form.password_field :password_confirmation, class:"form-control" , placeholder:t('confirmPassword') %>
                </div>

                <div class="form-group ">
                  <label>Status</label>
                  <%= form.select :status, [['Ativo', 1], ['Inativo', '2']], {},{:class=>'form-control'} %>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
              <%= form.submit t('register'), class:"btn btn-primary"  %>
              <%= link_to t('cancel'), usuarios_path, type:'button', class: "btn btn-secondary" %>
              </div>
            <% end %>
          </div>
          <!-- /.box -->
  </section>    

  
                    

app/views/usuarios/desativar.html.erb
<h1>desativando Usuario</h

app/views/usuarios/edit.html.erb
<%= render 'form', usuario: @usuario %>
<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<div class="col-sm-6">
  <h1><i class="fas fa-users"> </i> <%=t('users')%> </i></h1>
</div>
<!-- Main content -->
<section class="content">
  <!-- Default box -->
  <div class="card">
    <div class="card-header">
    <div id="notice"><%= notice %></div>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
   
      <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 1%">
                        #
                    </th>
                    <th style="width: 20%">
                        <%=t('fullname')%>
                    </th>
                    <th style="width: 15%">
                        E-mail
                    </th>
                    <th>
                        <%=t('dateIncluded')%>
                    </th>
                    <th style="width: 8%" class="text-center">
                        Status
                    </th>
                    <th style="width: 35%">
                    </th>
                </tr>
            </thead>
            <% @usuarios.each do |usuario| %>
              <tbody>
                  <tr>
                      <td>
                          #
                      </td>
                      <td>
                            <%= usuario.name %>
                      </td>
                      <td>
                        <%= usuario.email %>
                      </td>
                      <td>
                        <%= usuario.created_at %>
                      </td>
                      <td class="project-state">
                        <% if usuario.status==1 
                           classe = "badge badge-success"
                            valor = t('ativo')
                          else
                            classe = "badge badge-danger"
                            valor = t('inativo')
                          end
                        %>
                        <span class="<%=classe%>"><%= valor %></span>
                      </td>
                      <td class="project-actions text-right">
                          
                            <%= link_to  raw("#{t('edit')} <i class='fas fa-pencil-alt'></i>"), edit_usuario_path(usuario), type:'button', class: "btn btn-success btn-sm" %>
                        
                            <%= link_to raw("#{t('delete')} <i class='fas fa-trash-alt'></i>"), usuario, method: :delete, class: "btn btn-info btn-sm", data: { confirm: 'Are you sure?' } %>
                            
                         
                            
                            <%= link_to raw("#{t('ativar')} <i class='fas fa-share-square'></i>"), usuario, method: :desativar, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure ' + usuario.name+ ' ?' } %>
                            
                      </td>
                  </tr>
              </tbody>
            <%end%>
        </table>
      </div>
      <BR>

      <BR>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->

</section>
<div class="row">
<div class="col-md-12 text-right">
  <%= link_to t('newUser'), new_usuario_path, class: "btn btn-primary" %>
</div>
</div>
<!-- /.content -->

app/views/usuarios/new.html.erb
<%= render 'form', usuario: @usuario %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usuario.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @usuario.password_digest %>
</p>

<p>
  <strong>Status:</strong>
  <%= @usuario.status %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>